### ISSUE TITLE
Any update for new versions of firebaseui? 

### ISSUE THREAD

**Issue by nikolas-nelson** [l0ll098/FirebaseUI-Angular#5]
With new version Firebase, Firebase ui and angular 13 i'm getting multiple errors. 

Error: export 'default' (imported as 'firebaseOriginal') was not found in 'firebase/app'

Error: export 'ɵfirebaseAppFactory' (imported as 'ɵfirebaseAppFactory') was not found in '@angular/fire'

error TS2305: Module '"@angular/fire/auth"' has no exported member 'AngularFireAuth'.

**Comment by l0ll098** [comment]
Hi @nikolas-nelson,
I've just released two new versions: the first one can be used with Angular 12, while the second release supports Angular 13.
Note that both of them require Firebase 9.

Since you are using Angular 13, make sure to install these dependencies:
| Angular | Firebase | AngularFire  | FirebaseUI | firebaseui-angular-i18n|
| --------|----------|--------------|------------|-------------------------|
| 13.0.0  | ^9.3.0   | ^7.1.1       | ^6.0.0     | 6.1.0

Once you do that, you should be good to go.
Please let me know if it worked so that I can close this issue :)

**Comment by nikolas-nelson** [comment]
Hi, now it works great, thx for quick fix.
